ARM64: configs: stock_defconfig: Enable configs required by Kernel FCM 6
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatib
le: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    For config CONFIG_ANDROID_LOW_MEMORY_KILLER, value = y but required n
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_SONY_FF
    Missing config CONFIG_XFRM_MIGRATE
: Success

Change-Id: I7a9b05fa282c12ee1c17ffa1fe89a0688eb9b73b
Signed-off-by: lemezohaib <zhbkhan644@gmail.com>